name: Heroku Deployment

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: add dotenv
        run: dotnet add package 
      - name: Print MySQL Connection String
        run: |
          echo "MySQL Connection String: ${{ secrets.MYSQL_CONNECTION_STRING }}"

      - name: Log in to Heroku
        run: echo "$HEROKU_API_KEY" | docker login -u _ --password-stdin registry.heroku.com

      - name: Build and Push Docker Image
        run: |
          docker build --build-arg MYSQL_CONNECTION_STRING="${{ secrets.MYSQL_CONNECTION_STRING }}" -t registry.heroku.com/time-backend/web .

      - name: Heroku Push
        run: heroku container:push web -a time-backend
      - name: Release to Heroku
        run: heroku container:release web -a time-backend

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      MYSQL_CONNECTION_STRING: ${{secrets.MYSQL_CONNECTION_STRING}}
      
